---
title: "Analysis Brazil"
author: "Jan Mölich"
date: "11/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(skimr)
library(vroom)
library(stringr)
library(openxlsx)
library(Publish)
library(data.table)
library(tidyverse)
library(moderndive)
library(huxtable)
library(here)
library(broom)


# to create a scatterplot matrix
library(GGally)

# The broom package lets us manipulate model objects and makes it easier to
# generate predictions and plot them
library(broom)

#to check collinearity, we calculate VIF, Variance Inflation Factor
library(car)
```


```{r}

## Importing Data
brazil_covid19 <- vroom("brazil_covid19.csv")
brazil_cities <- vroom("brazil_covid19_cities.csv")
brazil_city_coordinates <- vroom("brazil_cities_coordinates.csv")
brazil_population <- vroom(file = "pop_by_city.csv")
brazil_gdp <- vroom("PIB dos Munic¡pios - base de dados 2010-2017.csv")
brazil_gdp_location <- read.xlsx(xlsxFile = "brazil_gdp_city.xlsx", fillMergedCells = TRUE, colNames = TRUE) 

brazil_gdp_location <- brazil_gdp_location %>% 
  janitor::clean_names() %>% 
  rename(
    city_name = municipio,
    class = classes_de_rendimento_nominal_mensal_domiciliar_per_capita,
    statistic = ano_x_situacao_do_domicilio
    ) %>% 
  filter(class != "Total") %>% 
  mutate(class = case_when(
    class == "Total" ~ "Total",
    class == "Até 1/8 de salário mínimo" ~ "below_0.125",
    class == "Mais de 1/8 a 1/4 de salário mínimo" ~ "between_0.125_0.25",
    class == "Mais de 1/4 a 1/2 salário mínimo" ~ "between_0.25_0.5",
    class == "Mais de 1/2 a 1 salário mínimo" ~ "between_0.5_1",
    class == "Mais de 1 a 2 salários mínimos" ~ "between_1_2",
    class == "Mais de 2 a 3 salários mínimos" ~ "between_2_3",
    class == "Mais de 3 a 5 salários mínimos" ~ "between_3_5",
    class == "Mais de 5 a 10 salários mínimos" ~ "between_5_10",
    class == "Mais de 10 salários mínimos" ~ "more_than_10",
    TRUE ~ class),
    city_name = str_remove(city_name, " \\([A-Z]{2}\\)")) %>% 
  mutate(statistic = round(as.numeric(statistic),2)) %>% 
  filter(class != "Sem rendimento", class != "Fonte: IBGE - Censo Demográfico") 
  
max_classes <- brazil_gdp_location %>% 
  group_by(city_name) %>% 
  arrange(desc(statistic)) %>% 
  drop_na(statistic) %>% 
  summarise(statistic=max(statistic))
  
max_classes_with_name <- max_classes  %>% 
  left_join(brazil_gdp_location, by=c("city_name", "statistic")) %>% 
  mutate(max_class = class) %>% 
  select(city_name, max_class)
  
brazil_gdp_location <- brazil_gdp_location %>% 
  left_join(max_classes_with_name, by="city_name") %>% 
  pivot_wider(names_from = class, values_from = statistic,values_fn = {mean})

brazil_city_coordinates <- brazil_city_coordinates %>% 
  mutate(city_code = as.numeric(substr(city_code, 1, 6)))

#DELETE
#brazil_gdp %>% filter(str_detect(nome,"ana"))
#brazil_cities %>% filter(str_detect(name,"Sant'Ana"))

#Cleaning the population db
brazil_population <- brazil_population %>% 
  janitor::clean_names() %>% 
  mutate(city_code = as.numeric(paste(cod_uf,substr(cod_munic, 1, 4), sep = "")), 
         population = case_when(
      city_code == 110020 ~ 369259,
      TRUE  ~ sapply(populacao_estimada, function(v) {as.numeric(gsub("\\.","", as.character(v)))}))) %>% 
  select(city_code, population)

#Cleaning the GDP db
brazil_gdp <- 
  brazil_gdp %>% 
  #selecting year
  filter(Ano == 2017) %>%
  #cleaning col names
  janitor::clean_names() %>% 
  #selecting columns
  select(c(nome_da_grande_regiao,
           codigo_do_municipio,
           nome_do_municipio,
           hierarquia_urbana_principais_categorias,
           produto_interno_bruto_a_precos_correntes_r_1_000,
           produto_interno_bruto_per_capita_a_precos_correntes_r_1_00,
           atividade_com_maior_valor_adicionado_bruto
           )) %>% 
  #renaming columns
  rename(region = nome_da_grande_regiao,
         city_code = codigo_do_municipio,
         city = nome_do_municipio,
         city_type = hierarquia_urbana_principais_categorias,
         gdp = produto_interno_bruto_a_precos_correntes_r_1_000,
         gdp_per_capita = produto_interno_bruto_per_capita_a_precos_correntes_r_1_00,
         main_activity = atividade_com_maior_valor_adicionado_bruto) %>% 
  #replacing decimal and thousand separators
  mutate(gdp = sapply(gdp, function(v) {as.numeric(gsub("\\,","", as.character(v)))}),
         gdp_per_capita = sapply(gdp_per_capita, function(v) {as.numeric(gsub("\\,","", as.character(v)))})) %>% 
  #removing last digit from the city code
  mutate(city_code = as.integer(substr(city_code, 1, nchar(city_code)-1)))


#Joining databases (coordinates and population)
brazil_cities <- brazil_cities %>% 
  left_join(brazil_city_coordinates, by = c("code" = "city_code")) %>% 
  left_join(brazil_population,by = c("code" = "city_code")) %>% 
  left_join(brazil_gdp,by = c("code" = "city_code")) %>% 
  left_join(brazil_gdp_location,by = c("name" = "city_name"))

#Creating daily_new_cases and cases_per_100k
brazil_cities <- brazil_cities %>% 
  arrange(code, date) %>% 
  group_by(code) %>% 
  mutate(daily_new_cases = cases - lag(cases),
         weekly_new_cases = cases - lag(cases, k=7),
         weekly_cases_per_100k = (weekly_new_cases / population) * 100000)

#Creating daily_new_deaths and deaths_per_100k
brazil_cities <- brazil_cities %>% 
  arrange(code, date) %>% 
  group_by(code) %>% 
  mutate(daily_new_deaths = deaths - lag(deaths),
         weekly_new_deaths = deaths - lag(deaths, k=7),
         weekly_deaths_per_100k = (weekly_new_deaths / population) * 100000)

#Creating daily_new_deaths and deaths_per_100k
brazil_cities <- brazil_cities %>% 
  arrange(code, date) %>% 
  group_by(code) %>% 
  mutate(active_infections = cases - lag(cases,14),
         recovered_infections = lag(cases,14) - deaths)


write.csv(brazil_cities,"brazil_cities_lat_long.csv")
```


```{r}

brazil_cities <- brazil_cities %>% mutate(daily_new_cases = ifelse(is.na(daily_new_cases),0 , daily_new_cases))


#Creating vraibles about region: daily_cases / cumsum(cases) / days_since 10000 cases
brazil_cities_region <- brazil_cities %>%
  arrange(region, date) %>% 
  group_by(region,date) %>%
  summarise(daily_cases_region= sum(daily_new_cases)) %>% 
  mutate(cumsum_region= cumsum(daily_cases_region))%>% 
  mutate(region_days_since_10000_cases = ifelse (cumsum_region < 10000,0,1))%>% 
  mutate(region_days_since_10000_cases = ifelse (cumsum_region< 10000,0, cumsum(region_days_since_10000_cases) )) 

#Creating variables by city type
brazil_cities_type <- brazil_cities %>%
  arrange(city_type, date) %>% 
  group_by(city_type,date) %>%
  summarise(daily_cases_region= sum(daily_new_cases)) %>% 
  mutate(cumsum_city_type= cumsum(daily_cases_region))%>% 
  mutate(city_type_days_since_10000_cases = ifelse (cumsum_city_type < 10000,0,1))%>% 
  mutate(city_type_days_since_10000_cases = ifelse (cumsum_city_type< 10000,0, cumsum(city_type_days_since_10000_cases) )) 

#Creating variable by states
brazil_cities_states <- brazil_cities %>%
  arrange(state, date) %>% 
  group_by(state,date) %>%
  summarise(daily_cases_region= sum(daily_new_cases)) %>% 
  mutate(cumsum_states= cumsum(daily_cases_region))%>% 
  mutate(states_days_since_10000_cases = ifelse (cumsum_states < 10000,0,1))%>% 
  mutate(states_days_since_10000_cases = ifelse (cumsum_states< 10000,0, cumsum(states_days_since_10000_cases) ))
 

brazil_cities <- brazil_cities %>% mutate(population = ifelse(is.na(daily_new_cases), 0 , population))

brazil_cities_gdp <- brazil_cities


#Categorizing gdp
brazil_cities_gdp <- brazil_cities_gdp %>% 
  mutate(gdp_group = case_when(
    gdp_per_capita <= 10000 ~ 1,
    gdp_per_capita <= 20000 ~ 2,
    gdp_per_capita <= 30000 ~ 3,
    gdp_per_capita <= 40000 ~ 4,
    gdp_per_capita >= 40000 ~ 5
  ))

#Creating variables by gdp
brazil_cities_gdp <- brazil_cities_gdp %>%
  arrange(gdp_group, date) %>% 
  group_by(gdp_group,date) %>%
  summarise(daily_cases_region= sum(daily_new_cases)) %>% 
  mutate(cumsum_gdp= cumsum(daily_cases_region))%>% 
  mutate(gdp_days_since_10000_cases = ifelse (cumsum_gdp < 10000,0,1))%>% 
  mutate(gdp_days_since_10000_cases = ifelse (cumsum_gdp< 10000,0, cumsum(gdp_days_since_10000_cases) ))


#Creating csv for tableau
write.csv(brazil_cities_region,"brazil_cities_region.csv")
write.csv(brazil_cities_states,"brazil_cities_states.csv")
write.csv(brazil_cities_type, "brazil_cities_type.csv")
write.csv(brazil_cities_gdp, "brazil_cities_gdp.csv")




```





```{r}

# Quick visualistaions 
ggplot(brazil_cities_region, aes(x= region_days_since_10000_cases, y= cumsum_region, color=region))+ geom_point()+ labs(title = "Spreading of COVID19 by region")

ggplot(brazil_cities_type, aes(x= city_type_days_since_10000_cases, y= cumsum_city_type, color=city_type))+ geom_point() +labs(title = "Spreading of COVID19 by city_type")

ggplot(brazil_cities_states, aes(x= states_days_since_10000_cases, y= cumsum_states, color=state))+ geom_point() +labs(title = "Spreading of COVID19 by states")


ggplot(brazil_cities_gdp, aes(x= gdp_days_since_10000_cases, y= cumsum_gdp, color=gdp_group))+ geom_point()+labs(title = "Spreading of COVID19 by gdp")



```

```{r}
##Regression

#joining database in order to use some variable for the regression

brazil_cities_2 <- brazil_cities %>% 
  left_join(brazil_cities_region, by = c("region" = "region", "date"="date")) %>% 
  left_join(brazil_cities_type,by = c("city_type" = "city_type","date"="date")) %>% 
  left_join(brazil_cities_states,by = c("state" = "state", "date"="date")) 


  view(brazil_cities_2)

#First model
brazil_new_cases <- brazil_cities_2


brazil_new_cases_1 <- brazil_new_cases %>%  lm(daily_new_cases ~ region + gdp_per_capita + region_days_since_10000_cases + city_type_days_since_10000_cases + city_type + states_days_since_10000_cases + population , data = brazil_new_cases)

brazil_new_cases_1 %>% tidy(conf.int=TRUE) 

#Second model / not optimal as we are creating value for variables in order to predict the daily_new_cases
brazil_new_cases_2 <- brazil_cities_2

brazil_new_cases_2 <- brazil_new_cases %>%  lm(daily_new_cases ~ region + gdp_per_capita + region_days_since_10000_cases + city_type_days_since_10000_cases + city_type + states_days_since_10000_cases + population + deaths + cases + weekly_cases_per_100k + weekly_deaths_per_100k, data = brazil_new_cases)

brazil_new_cases_2 %>% tidy(conf.int=TRUE)





```

```{r}

```


